### ISSUE TITLE
Show Module NavBar when not logged it.

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#27]
As a way to standarize the behaviour of all modules inside the Master App, please put the nav bar even when the user is not logged in, removing the buttons that give access to the logged in functionality

![image](https://user-images.githubusercontent.com/9479367/47600363-5bafdb80-d9c0-11e8-9793-da78a903ad0b.png)

**Comment by bearcanrun** [comment]
Obsolete due to new BannerTopBar
