### ISSUE TITLE
Improve aesthetics of Your Teams component

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#29]
![image](https://user-images.githubusercontent.com/9479367/47601875-d257d380-d9d6-11e8-8613-a56c0eef5835.png)

1. This title seems to be unnecesary
2. This date is not needed
3. This card would be better in a grid format, or a list with some margin left and right

**Comment by bearcanrun** [comment]
Fixed in #70
