### ISSUE TITLE
No way to create more than one team?

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#30]
Is this an intentional restriction?

![image](https://user-images.githubusercontent.com/9479367/47601913-4003ff80-d9d7-11e8-870a-77ac38b14fca.png)

**Comment by bearcanrun** [comment]
Yes. Currently limited to one team. The functionality to allow more teams exists, but the interplay between teams with multiple members and multiple financial beings needs to be strategized first.
