### ISSUE TITLE
Use standard way to communicate a piece of functionality is not ready yet

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#31]
One example of where this is needed is here>

![image](https://user-images.githubusercontent.com/9479367/47601932-88232200-d9d7-11e8-8fb4-412f5214a630.png)

The way it should be is the one used at the Users Module>

![image](https://user-images.githubusercontent.com/9479367/47601940-a25d0000-d9d7-11e8-8b4a-752d4b79b6e3.png)

**Comment by bearcanrun** [comment]
Fixed in #70
