### ISSUE TITLE
Edit Team should be Team profile Page in editable mode

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#33]
In fact there is no difference for a user between the Team Profile Page for viewing purposes than for editing purposes. In both cases it is the same content, with the difference that if you have the rights to modify some stuff, you will be able to do it right away, buy clicking on the fields, or discovering with a mouse over the button to change an image for example.

Current view is the following.

![image](https://user-images.githubusercontent.com/9479367/47602008-a76e7f00-d9d8-11e8-8cd0-a52c41d574b9.png)

**Comment by bearcanrun** [comment]
Fixed in #70
