### ISSUE TITLE
New Team Component

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#37]
Current Component does not look well enough.

![image](https://user-images.githubusercontent.com/9479367/47602168-edc4dd80-d9da-11e8-90a9-65423e6c624a.png)

**Comment by Luis-Fernando-Molina** [comment]
1. that label should be removed.
2. That space should be standarized both left and right like in the image below belonging to the User Module.
3. This should be replaced with a proper title and a paragraph explaining the basics.

possible title: Create a new Team
possible paragraph: You have the right to have your own team. Once you create one, you will be able to invite people to join it and together you can create bots of different types and then put them to compete, win prizes and more.  Start by filling the required information below.

This next modal, should be turned into a sheet similar to the next image, taken from the User Module.

![image](https://user-images.githubusercontent.com/9479367/47602198-abe86700-d9db-11e8-93bd-9a3118958c49.png)

It should end up looking like this, so that we preserve a standard way across all modules.

![image](https://user-images.githubusercontent.com/9479367/47602209-dd613280-d9db-11e8-976c-b1e3b24cb9dc.png)


4. That should be replaced by an orange button "Create New Team"

**Comment by bearcanrun** [comment]
Fixed in #70
