### ISSUE TITLE
Improve the texts of these paragraphs

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#38]
1. Put something more meaningful
2. End users dont need to know this. Just remove it or replace it with something more meaningful.

![image](https://user-images.githubusercontent.com/9479367/47602246-6f693b00-d9dc-11e8-8e1a-eff0d0d074f7.png)

**Comment by Luis-Fernando-Molina** [comment]
According to this https://github.com/AdvancedAlgos/TeamsModule/issues/37 this modal should end up in a normal screen component.

**Comment by bearcanrun** [comment]
Fixed in #70
