### ISSUE TITLE
Team Details needs improvements on its design

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#64]
Even though we have not defined the standards for the look and field of these type of pop ups, some stuff is emerging from other modules. This particular components contrasts with the aesthetics of the rest of the app. Here are some suggestions>

![image](https://user-images.githubusercontent.com/9479367/48468340-d6179280-e7eb-11e8-81d1-70f1c0f82ab0.png)

**Comment by bearcanrun** [comment]
Fixed in #70
