### ISSUE TITLE
Improve look and feel of Edit Team component

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#65]
It doesnt seems to be a defined criteria across the module on how the buttons should be or where they should be. In forms like this, we are putting one orange button at the center / botton, of the size of the text.

Also the rest of the things highlighted need to be improved in order for this component to pass the minimun requirements of look and feel.

![image](https://user-images.githubusercontent.com/9479367/48468523-6d7ce580-e7ec-11e8-8520-609365346888.png)

**Comment by bearcanrun** [comment]
Fixed in #70
