### ISSUE TITLE
Inconsistency on the size of the cards

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#67]
This card doesnt look like the others at the same module. Please put it of the same dimmensions than the ones at YOUR TEAMS.

![image](https://user-images.githubusercontent.com/9479367/48469901-3e687300-e7f0-11e8-9166-5eb623ceccc2.png)

**Comment by Luis-Fernando-Molina** [comment]
Also, correct the margins please to the same used at YOUR TEAMS

**Comment by bearcanrun** [comment]
Fixed in #70
