### ISSUE TITLE
Avatar Change text without correct font

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#69]
Also, the CANCEL option should be some X icon at the top right border

![image](https://user-images.githubusercontent.com/9479367/48470353-7b813500-e7f1-11e8-8716-1c752f19b2ac.png)

**Comment by bearcanrun** [comment]
Moved to [WebComponents #2](https://github.com/AdvancedAlgos/WebComponents/issues/2)
