### ISSUE TITLE
Team created but can not see it at MY TEAMS

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [AdvancedAlgos/TeamsModule#75]
This is the team I have just created:

![image](https://user-images.githubusercontent.com/9479367/48675956-2d0cc700-eb60-11e8-8479-a7ce7b291a90.png)

I can not see it at MY TEAMS

![image](https://user-images.githubusercontent.com/9479367/48675964-44e44b00-eb60-11e8-96f4-491e125b6a20.png)

I have received this email though:

![image](https://user-images.githubusercontent.com/9479367/48675975-68a79100-eb60-11e8-9805-b75ac20c7096.png)

**Comment by Luis-Fernando-Molina** [comment]
Additional info>

![image](https://user-images.githubusercontent.com/9479367/48676013-e4094280-eb60-11e8-8f89-1bfe9b10b98e.png)

**Comment by Luis-Fernando-Molina** [comment]
I loggged out and logged in again and the same thing happens.

**Comment by Luis-Fernando-Molina** [comment]
If I try to add a key, the key vault says I have no bots yet.

![image](https://user-images.githubusercontent.com/9479367/48676073-d1433d80-eb61-11e8-8420-78f843f6cfa4.png)

**Comment by bearcanrun** [comment]
Try resetting/empty cache of browser to make sure you're running latest version of client.

**Comment by Luis-Fernando-Molina** [comment]
This does not work for me.

**Comment by bearcanrun** [comment]
Caused by user created twice. Redirecting to [Users Module #32](https://github.com/AdvancedAlgos/UsersModule/issues/32)
